var customflairs = [
	{
		name: "degree/eagle",
		description: "Fly!",
		crop: [96, 16, 16, 16],
		price: 200,
	},
	{
		name: "degree/cloudy",
		description: "It's cloudy today.",
		crop: [0, 0, 16, 16],
		price: 200,
	},
	{
		name: "degree/partially Cloudy",
		description: "It's a bit cloudy today.",
		crop: [16, 0, 16, 16],
		price: 200,
	},
	{
		name: "degree/storm",
		description: "It's storming today.",
		crop: [32, 0, 16, 16],
		price: 200,
	},
	{
		name: "degree/sapphire",
		description: "Shiny Blue.",
		crop: [0, 16, 16, 16],
		price: 200,
	},
	{
		name: "degree/ruby",
		description: "Shiny Red.",
		crop: [32, 16, 16, 16],
		price: 200,
	},
	{
		name: "degree/emerald",
		description: "Shiny Green.",
		crop: [16, 16, 16, 16],
		price: 200,
	},
	{
		name: "degree/life-ring",
		description: "Grab on to this!",
		crop: [0, 32, 16, 16],
		price: 200,
	},
	{
		name: "degree/light-bulb",
		description: "I have an idea!",
		crop: [16, 32, 16, 16],
		price: 200,
	},
	{
		name: "degree/magnet",
		description: "Attraction.",
		crop: [32, 32, 16, 16],
		price: 200,
	},
	{
		name: "degree/dollar-sign",
		description: "$$$$$$",
		crop: [48, 32, 16, 16],
		price: 200,
	},
	{
		name: "degree/pill",
		description: "Red or Blue? or the Red and White one?",
		crop: [64, 32, 16, 16],
		price: 200,
	},
	{
		name: "degree/cards",
		description: "Bluffed.",
		crop: [80, 32, 16, 16],
		price: 200,
	},
	{
		name: "degree/blue-flag",
		description: "This is the blue teams flag.",
		crop: [96, 32, 16, 16],
		price: 200,
	},
	{
		name: "degree/red-flag",
		description: "This is the red teams flag.",
		crop: [112, 32, 16, 16],
		price: 200,
	},
	{
		name: "degree/neutral-flag",
		description: "This is everyone's Flag",
		crop: [112, 16, 16, 16],
		price: 200,
	},
	{
		name: "degree/bug",
		description: "This script is full of 'em.",
		crop: [48, 16, 16, 16],
		price: 200,
	},
	{
		name: "degree/camera",
		description: "Snap!",
		crop: [64, 16, 16, 16],
		price: 200,
	},
	{
		name: "degree/werid-egg",
		description: "Don't know what's in it but its weird.",
		crop: [80, 0, 16, 16],
		price: 200,
	},
	{
		name: "degree/star",
		description: "That's what you are!",
		crop: [112, 0, 16, 16],
		price: 200,
	},
	{
		name: "degree/8-Bit Bomb",
		description: "*Pixelized Boom Sound*",
		crop: [48, 0, 16, 16],
		price: 200,
	},
	{
		name: "degree/parrot",
		description: "Stop Mocking me. yOu StOp mOCkINg mE.",
		crop: [96, 0, 16, 16],
		price: 200,
	},
	{
		name: "degree/iceberg",
		description: "Chill.",
		crop: [64, 0, 16, 16],
		price: 200,
	},
  {
		name: "degree/iceberg",
		description: "Chill.",
		crop: [64, 0, 16, 16],
		price: 200,
	},
  {
		name: "degree/android",
		description: "They make phones.",
		crop: [0, 80, 16, 16],
		price: 200,
	},
  {
		name: "degree/apple",
		description: "One a day Keeps the noobs away.",
		crop: [16, 80, 16, 16],
		price: 200,
	},
  {
		name: "degree/battery",
		description: "It's a D type.",
		crop: [32, 80, 16, 16],
		price: 200,
	},
  {
		name: "degree/bomb",
		description: "Boom.",
		crop: [48, 80, 16, 16],
		price: 200,
	},
  {
		name: "degree/gear",
		description: "Solid and made out of metal.",
		crop: [64, 80, 16, 16],
		price: 200,
	},
  {
		name: "degree/chat Bubble",
		description: "I'd like to have a little chat with you.",
		crop: [80, 80, 16, 16],
		price: 200,
	},
  {
		name: "degree/controller",
		description: "Xbox ones are the most ergonomic.",
		crop: [96, 80, 16, 16],
		price: 200,
	},
  {
		name: "degree/donut",
		description: "White Frosted Goodness.",
		crop: [112, 80, 16, 16],
		price: 200,
	},
  {
		name: "degree/bandaid",
		description: "Apply firmly to ankles.",
		crop: [0, 96, 16, 16],
		price: 200,
	},
	{
		name: "degree/baton",
		description: "STOP RESISTING!",
		crop: [16, 96, 16, 16],
		price: 200,
	},
	{
		name: "degree/alarm",
		description: "RED SPY IN THE BASE!",
		crop: [32, 96, 16, 16],
		price: 200,
	},
	{
		name: "degree/boomerang",
		description: "First one was made in 1798.",
		crop: [48, 96, 16, 16],
		price: 200,
	},
	{
		name: "degree/compass",
		description: "Find your way.",
		crop: [64, 96, 16, 16],
		price: 200,
	},
	{
		name: "degree/ship",
		description: "Everyone aboard the S.S. Showboat!",
		crop: [80, 96, 16, 16],
		price: 200,
	},
	{
		name: "degree/dog",
		description: "Woof.",
		crop: [96, 96, 16, 16],
		price: 200,
	},
	{
		name: "degree/pan",
		description: "The Deadliest Weapon of all.",
		crop: [112, 96, 16, 16],
		price: 200,
	},
	{
		name: "degree/car",
		description: "VRROOOOMMMMM.",
		crop: [0, 112, 16, 16],
		price: 200,
	},
	{
		name: "degree/chair",
		description: "The swivel ones are fun.",
		crop: [16, 112, 16, 16],
		price: 200,
	},
	{
		name: "degree/chameleon",
		description: "Slow and steady, sticks to the pace.",
		crop: [32, 112, 16, 16],
		price: 200,
	},
	{
		name: "degree/white-knight",
		description: "Literally.",
		crop: [48, 112, 16, 16],
		price: 200,
	},
	{
		name: "degree/cutlery",
		description: "We want to eat!",
		crop: [64, 112, 16, 16],
		price: 200,
	},
	{
		name: "degree/diamond",
		description: "Because your aunty loves diamonds.",
		crop: [80, 112, 16, 16],
		price: 200,
	},
	{
		name: "degree/drill",
		description: "DeWalt brand.",
		crop: [96, 112, 16, 16],
		price: 200,
	},
	{
		name: "degree/binoculars",
		description: "See those jukes from a mile away.",
		crop: [112, 112, 16, 16],
		price: 200,
	},
	{
		name: "degree/cat",
		description: "Meow.",
		crop: [0, 128, 16, 16],
		price: 200,
	},
	{
		name: "degree/checkerboard",
		description: "Checkmate.",
		crop: [16, 128, 16, 16],
		price: 200,
	},
	{
		name: "degree/chef-hat",
		description: "Crem Bru Lee.",
		crop: [32, 128, 16, 16],
		price: 200,
	},
	{
		name: "degree/clock",
		description: "Tick Tock.",
		crop: [48, 128, 16, 16],
		price: 200,
	},
	{
		name: "degree/die",
		description: "You roll a six. A fireball kills your elf companion.",
		crop: [64, 128, 16, 16],
		price: 200,
	},
	{
		name: "degree/dynamite",
		description: "It's Dynamite.",
		crop: [80, 128, 16, 16],
		price: 200,
	},
	{
		name: "degree/panda",
		description: "Panda. Panda Panda.",
		crop: [96, 128, 16, 16],
		price: 200,
	},
	{
		name: "degree/fire-extinguisher",
		description: "Pull, Aim, Squeeze, Sweep.",
		crop: [112, 128, 16, 16],
		price: 200,
	},
	{
		name: "degree/firefox",
		description: "Pull, Aim, Squeeze, Sweep.",
		crop: [0, 144, 16, 16],
		price: 200,
	},
	{
		name: "degree/canadian-flag",
		description: "Maple Syrup is it's biggest strength.",
		crop: [16, 144, 16, 16],
		price: 200,
	},
	{
		name: "degree/scope",
		description: "Headshot.",
		crop: [32, 144, 16, 16],
		price: 200,
	},
	{
		name: "degree/medkit",
		description: "The Medic's substitute.",
		crop: [48, 144, 16, 16],
		price: 200,
	},
	{
		name: "degree/helicopter",
		description: "Eyes in the sky.",
		crop: [64, 144, 16, 16],
		price: 200,
	},
	{
		name: "degree/origami",
		description: "I can make one that flaps it's wings.",
		crop: [80, 144, 16, 16],
		price: 200,
	},
	{
		name: "degree/pizza",
		description: "Pineapple Pizza is the best.",
		crop: [96, 144, 16, 16],
		price: 200,
	},
];